spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    mongodb:
      host: localhost
      port: 27017
      database: consumer

server:
  port: 8002